export default {
    "signin": "Sign In",
    "account": "Account",
    "password": "Password",
    "forgot password": "Forgot password ?",
    "remember me": "Remember me",
    "online": "Online",
    "search": "Search",
    "result": "Result",
    "results": "results",
    "general": "General",
    "my profile": "My Profile",
    "settings": "Settings",
    "help": "Help",
    "signout": "Sign Out",
    "dashboard": "Dashboard",
    "projects manager": "Project Manager",
    "accounts manager": "Accounts Manager",
    "tasks": "Tasks",
    "statistic": "Statistic",
    "about us": "About Us",
    "contacts": "Contacts",
    "404": "PAGE NOT FOUND",
    "settings.title": "Settings",
    "settings.desc": "Application global settings",
    "settings.languages": "Languages",

    "projects.title": "Projects",
    "projects.desc": "Project manager",
}