export default {
    "signin": "Đăng nhập",
    "account": "Tên đăng nhập",
    "password": "Mật khẩu",
    "forgot password": "Quên mật khẩu ?",
    "remember me": "Ghi nhớ đăng nhập",
    "online": "Trực tuyến",
    "general": "Tổng quan",
    "search": "Tìm kiếm",
    "result": "Kết quả",
    "results": "kết quả",
    "my profile": "Hồ sơ của tôi",
    "settings": "Cấu hình",
    "help": "Trợ giúp",
    "signout": "Đăng xuất",
    "dashboard": "Bảng điều khiển",
    "user info": "Xin chào",
    "projects manager": "Quản lý dự án",
    "accounts manager": "Quản lý tài khoản",
    "accounts list": "Dánh sách tài khoản",

    "report":"Báo cáo",
    "tasks": "Yêu cầu",
    "statistic": "Thống kê",
    "workflow": "Quy trình",
    "about us": "Giới thiệu",
    "contacts": "Liên hệ",
    "404": "KHÔNG TÌM THẤY",

    "settings.title": "Cấu hình",
    "settings.desc": "Cấu hình chung cho ứng dụng",
    "settings.languages": "Ngôn ngữ",
    "settings.color": "Màu sắc",
    "settings.color button": "Thay đổi",


    "projects.title": "Quản lý dự án",
    "users.title": "Quản lý người dùng",
   
}