export default {
    "signin": "Đăng nhập",
    "account": "Tên đăng nhập",
    "password": "Mật khẩu",
    "forgot password": "Quên mật khẩu ?",
    "remember me": "Ghi nhớ đăng nhập",
    "online": "Trực tuyến",
    "general": "Tổng quan",
    "search": "Tìm kiếm",
    "result": "Kết quả",
    "results": "kết quả",
    "my profile": "Hồ sơ của tôi",
    "settings": "Cấu hình",
    "help": "Trợ giúp",
    "signout": "Đăng xuất",
    "dashboard": "Bảng điều khiển",
    "projects manager": "Dự án",
    "accounts manager": "Tài khoản người dùng",
    "tasks": "Yêu cầu",
    "statistic": "Thống kê",
    "about us": "Giới thiệu",
    "contacts": "Liên hệ",
    "404": "KHÔNG TÌM THẤY",
    "settings.title": "Cấu hình",
    "settings.desc": "Cấu hình chung cho ứng dụng",
    "settings.languages": "Ngôn ngữ",

    "projects.title": "Dự án",
    "projects.desc": "Quản lý dự án",
}